source 'https://rubygems.org'

gem 'rails', '~> 5.0.0'
gem 'sprockets-rails', '~> 3.2.0'

gem 'puma'

gem 'pry'
gem 'pry-rails'
gem 'awesome_print'

gem 'exception_notification', '>= 4.0.1'

gem 'jquery-rails'

group :test, :development do
  gem 'better_errors'
  gem 'binding_of_caller'
end

group :assets do
  gem 'sass-rails', '~> 5.0.0'
  gem 'uglifier', '>= 1.3.0'
  gem 'therubyracer'
end

gem 'json_exceptions', path: '../../yggdra/plugins/json_exceptions'
gem 'autosvg', path: '../../yggdra/plugins/autosvg'

gem 'yggdra_plugins', path: '../../yggdra/plugins/yggdra_plugins'

gem 'extjs', path: '../../yggdra/plugins/extjs'
gem 'extgui', path: '../../yggdra/plugins/extgui'

gem 'core_extgui', path: '../../yggdra/plugins/core_extgui'
gem 'shop_extgui', path: '../../yggdra/plugins/shop_extgui'
gem 'acao_extgui', path: '../../acao_plugins/acao_extgui'

gem 'acao_cam', path: '../../acao_plugins/acao_cam'
