source 'https://rubygems.org'

gem 'rails', '~> 4.2.0'
gem 'responders'
gem 'rails-observers'
gem 'squeel', :git => 'https://github.com/activerecord-hackery/squeel.git'

gem 'pg'
gem 'tiny_tds'
gem 'activerecord-sqlserver-adapter'#, :git => 'https://github.com/rails-sqlserver/activerecord-sqlserver-adapter.git', :ref => 'e3bcabffd5b3f37c4bd8a56ede2f295b43b86008'

gem 'puma'

gem 'pry'
gem 'pry-rails'
gem 'awesome_print'
gem 'state_machine'
gem 'geocoder'
gem 'exception_notification', '>= 4.0.1'

gem 'scruffy'

source 'https://gems.sevio.it/' do
  gem 'vihai-password', '>= 1.2.0'
  gem 'active_rest', '~> 6.10.0'
end

group :test, :development do
  gem 'better_errors'
  gem 'binding_of_caller'
end

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

gem 'vihai-password-rails', :path => '../../yggdra/plugins/vihai_password_rails'

gem 'json_exceptions', :path => '../../yggdra/plugins/json_exceptions'

gem 'yggdra_plugins', :path => '../../yggdra/plugins/yggdra_plugins'
gem 'hel', :path => '../../yggdra/plugins/hel'

gem 'core_models', :path => '../../yggdra/plugins/core_models'
gem 'core_hel', :path => '../../yggdra/plugins/core_hel'

gem 'shop_models', :path => '../../yggdra/plugins/shop_models'
gem 'shop_hel', :path => '../../yggdra/plugins/shop_hel'

#gem 'flarc', :path => '../flarc'
