source 'https://rubygems.org'

gem 'rails', '~> 5.0.0'

gem 'pg'

gem 'puma'
gem 'puma-plugin-systemd'

gem 'pry'
gem 'pry-rails'
gem 'awesome_print'
gem 'geocoder'
gem 'exception_notification', '>= 4.2.0'

gem 'scruffy'

source 'https://gems.sevio.it/' do
  gem 'vihai-password', '>= 1.2.0'
  gem 'active_rest', '~> 7.0.0'
end

group :test, :development do
  gem 'better_errors'
  gem 'binding_of_caller'
end

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

gem 'vihai-password-rails', :path => '../../yggdra/plugins/vihai_password_rails'

gem 'json_exceptions', :path => '../../yggdra/plugins/json_exceptions'

gem 'hel', :path => '../../yggdra/plugins/hel'

gem 'rails_actor_model', path: '../../yggdra/plugins/rails_actor_model'
gem 'rails_amqp', path: '../../yggdra/plugins/rails_amqp'
gem 'amqp_ws_gw', path: '../../yggdra/plugins/amqp_ws_gw'

gem 'core_models', :path => '../../yggdra/plugins/core_models'
gem 'core_hel', :path => '../../yggdra/plugins/core_hel'

gem 'shop_models', :path => '../../yggdra/plugins/shop_models'
gem 'shop_hel', :path => '../../yggdra/plugins/shop_hel'

gem 'acao_models', :path => '../../acao_plugins/acao_models'
gem 'acao_hel', :path => '../../acao_plugins/acao_hel'

gem 'i18n_models', path: '../../yggdra/plugins/i18n_models'
gem 'i18n_hel', path: '../../yggdra/plugins/i18n_hel'

gem 'ml_models', path: '../../yggdra/plugins/ml_models'
gem 'ml_hel', path: '../../yggdra/plugins/ml_hel'

gem 'streaming_models', path: '../../yggdra/plugins/streaming_models'
gem 'streaming_hel', path: '../../yggdra/plugins/streaming_hel'
