source 'https://rubygems.org'

gem 'rails', '~> 5.2.0'

gem 'pg'

gem 'puma'

gem 'pry'
gem 'pry-rails'
gem 'awesome_print'
gem 'geocoder'
gem 'scruffy'
gem 'prawn'

gem 'airbrake'

source 'https://gems.sevio.it/' do
  gem 'puma-plugin-systemd'
  gem 'vihai-password', '>= 1.2.0'
  gem 'active_rest', '~> 10.0'
  gem 'rails_active_rest', '~> 1.0'
  gem 'vihai-password-rails'
  gem 'json_exceptions'
  gem 'rails_actor_model'
  gem 'rails_amqp'
end

group :test, :development do
  gem 'better_errors'
  gem 'binding_of_caller'
end

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

gem 'hel', :path => '../../yggdra/plugins/hel'

gem 'amqp_ws_gw', path: '../../yggdra/plugins/amqp_ws_gw'

gem 'core_models', :path => '../../yggdra/plugins/core_models'
gem 'core_hel', :path => '../../yggdra/plugins/core_hel'

#gem 'shop_models', :path => '../../yggdra/plugins/shop_models'
#gem 'shop_hel', :path => '../../yggdra/plugins/shop_hel'

gem 'acao_models', :path => '../../acao-plugins/acao_models'
gem 'acao_hel', :path => '../../acao-plugins/acao_hel'

gem 'i18n_models', path: '../../yggdra/plugins/i18n_models'
gem 'i18n_hel', path: '../../yggdra/plugins/i18n_hel'

gem 'ml_models', path: '../../yggdra/plugins/ml_models'
gem 'ml_hel', path: '../../yggdra/plugins/ml_hel'

gem 'streaming_models', path: '../../yggdra/plugins/streaming_models'
gem 'streaming_hel', path: '../../yggdra/plugins/streaming_hel'
