# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

#development:
#  adapter: sqlserver
#  mode: dblib
#  dataserver: acao_sql_server
#  database: 
#  username: orlandi
#  password: orlandi

development:
  adapter: postgresql
  encoding: unicode
  database: acao
  username:
  password:

production:
  adapter: sqlserver
  mode: dblib
  dataserver: acao_sql_server
  database: 
  username: orlandi
  password: orlandi

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
